# Generated by Django 3.2.3 on 2021-06-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icecream_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
