# Generated by Django 3.2.3 on 2021-06-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icecream_app', '0002_delete_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clients',
            new_name='Contact',
        ),
    ]
